// All currencies available in iOS 18 Calculator (ISO code → display info)
export const ALL_CURRENCIES = {
  aed: { label: 'UAE Dirham', flag: '🇦🇪', code: 'AED' },
  afn: { label: 'Afghan Afghani', flag: '🇦🇫', code: 'AFN' },
  all: { label: 'Albanian Lek', flag: '🇦🇱', code: 'ALL' },
  amd: { label: 'Armenian Dram', flag: '🇦🇲', code: 'AMD' },
  ang: { label: 'Netherlands Antillean Guilder', flag: '🇳🇱', code: 'ANG' },
  aoa: { label: 'Angolan Kwanza', flag: '🇦🇴', code: 'AOA' },
  ars: { label: 'Argentine Peso', flag: '🇦🇷', code: 'ARS' },
  aud: { label: 'Australian Dollar', flag: '🇦🇺', code: 'AUD' },
  azn: { label: 'Azerbaijani Manat', flag: '🇦🇿', code: 'AZN' },
  bam: { label: 'Bosnia-Herzegovina Convertible Mark', flag: '🇧🇦', code: 'BAM' },
  bbd: { label: 'Barbadian Dollar', flag: '🇧🇧', code: 'BBD' },
  bdt: { label: 'Bangladeshi Taka', flag: '🇧🇩', code: 'BDT' },
  bgn: { label: 'Bulgarian Lev', flag: '🇧🇬', code: 'BGN' },
  bhd: { label: 'Bahraini Dinar', flag: '🇧🇭', code: 'BHD' },
  bnd: { label: 'Brunei Dollar', flag: '🇧🇳', code: 'BND' },
  bob: { label: 'Bolivian Boliviano', flag: '🇧🇴', code: 'BOB' },
  brl: { label: 'Brazilian Real', flag: '🇧🇷', code: 'BRL' },
  bsd: { label: 'Bahamian Dollar', flag: '🇧🇸', code: 'BSD' },
  btn: { label: 'Bhutanese Ngultrum', flag: '🇧🇹', code: 'BTN' },
  bwp: { label: 'Botswanan Pula', flag: '🇧🇼', code: 'BWP' },
  byn: { label: 'Belarusian Ruble', flag: '🇧🇾', code: 'BYN' },
  bzd: { label: 'Belize Dollar', flag: '🇧🇿', code: 'BZD' },
  cad: { label: 'Canadian Dollar', flag: '🇨🇦', code: 'CAD' },
  cdf: { label: 'Congolese Franc', flag: '🇨🇩', code: 'CDF' },
  chf: { label: 'Swiss Franc', flag: '🇨🇭', code: 'CHF' },
  clp: { label: 'Chilean Peso', flag: '🇨🇱', code: 'CLP' },
  cny: { label: 'Chinese Yuan', flag: '🇨🇳', code: 'CNY' },
  cop: { label: 'Colombian Peso', flag: '🇨🇴', code: 'COP' },
  crc: { label: 'Costa Rican Colón', flag: '🇨🇷', code: 'CRC' },
  cve: { label: 'Cape Verdean Escudo', flag: '🇨🇻', code: 'CVE' },
  czk: { label: 'Czech Koruna', flag: '🇨🇿', code: 'CZK' },
  djf: { label: 'Djiboutian Franc', flag: '🇩🇯', code: 'DJF' },
  dkk: { label: 'Danish Krone', flag: '🇩🇰', code: 'DKK' },
  dop: { label: 'Dominican Peso', flag: '🇩🇴', code: 'DOP' },
  dzd: { label: 'Algerian Dinar', flag: '🇩🇿', code: 'DZD' },
  egp: { label: 'Egyptian Pound', flag: '🇪🇬', code: 'EGP' },
  etb: { label: 'Ethiopian Birr', flag: '🇪🇹', code: 'ETB' },
  eur: { label: 'Euro', flag: '🇪🇺', code: 'EUR' },
  fjd: { label: 'Fijian Dollar', flag: '🇫🇯', code: 'FJD' },
  gbp: { label: 'British Pound', flag: '🇬🇧', code: 'GBP' },
  gel: { label: 'Georgian Lari', flag: '🇬🇪', code: 'GEL' },
  ghs: { label: 'Ghanaian Cedi', flag: '🇬🇭', code: 'GHS' },
  gmd: { label: 'Gambian Dalasi', flag: '🇬🇲', code: 'GMD' },
  gnf: { label: 'Guinean Franc', flag: '🇬🇳', code: 'GNF' },
  gtq: { label: 'Guatemalan Quetzal', flag: '🇬🇹', code: 'GTQ' },
  gyd: { label: 'Guyanaese Dollar', flag: '🇬🇾', code: 'GYD' },
  hkd: { label: 'Hong Kong Dollar', flag: '🇭🇰', code: 'HKD' },
  hnl: { label: 'Honduran Lempira', flag: '🇭🇳', code: 'HNL' },
  hrk: { label: 'Croatian Kuna', flag: '🇭🇷', code: 'HRK' },
  htg: { label: 'Haitian Gourde', flag: '🇭🇹', code: 'HTG' },
  huf: { label: 'Hungarian Forint', flag: '🇭🇺', code: 'HUF' },
  idr: { label: 'Indonesian Rupiah', flag: '🇮🇩', code: 'IDR' },
  ils: { label: 'Israeli Shekel', flag: '🇮🇱', code: 'ILS' },
  inr: { label: 'Indian Rupee', flag: '🇮🇳', code: 'INR' },
  iqd: { label: 'Iraqi Dinar', flag: '🇮🇶', code: 'IQD' },
  irr: { label: 'Iranian Rial', flag: '🇮🇷', code: 'IRR' },
  isk: { label: 'Icelandic Króna', flag: '🇮🇸', code: 'ISK' },
  jmd: { label: 'Jamaican Dollar', flag: '🇯🇲', code: 'JMD' },
  jod: { label: 'Jordanian Dinar', flag: '🇯🇴', code: 'JOD' },
  jpy: { label: 'Japanese Yen', flag: '🇯🇵', code: 'JPY' },
  kes: { label: 'Kenyan Shilling', flag: '🇰🇪', code: 'KES' },
  kgs: { label: 'Kyrgystani Som', flag: '🇰🇬', code: 'KGS' },
  khr: { label: 'Cambodian Riel', flag: '🇰🇭', code: 'KHR' },
  kmf: { label: 'Comorian Franc', flag: '🇰🇲', code: 'KMF' },
  krw: { label: 'South Korean Won', flag: '🇰🇷', code: 'KRW' },
  kwd: { label: 'Kuwaiti Dinar', flag: '🇰🇼', code: 'KWD' },
  kzt: { label: 'Kazakhstani Tenge', flag: '🇰🇿', code: 'KZT' },
  lak: { label: 'Laotian Kip', flag: '🇱🇦', code: 'LAK' },
  lbp: { label: 'Lebanese Pound', flag: '🇱🇧', code: 'LBP' },
  lkr: { label: 'Sri Lankan Rupee', flag: '🇱🇰', code: 'LKR' },
  lrd: { label: 'Liberian Dollar', flag: '🇱🇷', code: 'LRD' },
  lsl: { label: 'Lesotho Loti', flag: '🇱🇸', code: 'LSL' },
  lyd: { label: 'Libyan Dinar', flag: '🇱🇾', code: 'LYD' },
  mad: { label: 'Moroccan Dirham', flag: '🇲🇦', code: 'MAD' },
  mdl: { label: 'Moldovan Leu', flag: '🇲🇩', code: 'MDL' },
  mga: { label: 'Malagasy Ariary', flag: '🇲🇬', code: 'MGA' },
  mkd: { label: 'Macedonian Denar', flag: '🇲🇰', code: 'MKD' },
  mmk: { label: 'Myanmar Kyat', flag: '🇲🇲', code: 'MMK' },
  mnt: { label: 'Mongolian Tugrik', flag: '🇲🇳', code: 'MNT' },
  mop: { label: 'Macanese Pataca', flag: '🇲🇴', code: 'MOP' },
  mur: { label: 'Mauritian Rupee', flag: '🇲🇺', code: 'MUR' },
  mvr: { label: 'Maldivian Rufiyaa', flag: '🇲🇻', code: 'MVR' },
  mwk: { label: 'Malawian Kwacha', flag: '🇲🇼', code: 'MWK' },
  mxn: { label: 'Mexican Peso', flag: '🇲🇽', code: 'MXN' },
  myr: { label: 'Malaysian Ringgit', flag: '🇲🇾', code: 'MYR' },
  mzn: { label: 'Mozambican Metical', flag: '🇲🇿', code: 'MZN' },
  nad: { label: 'Namibian Dollar', flag: '🇳🇦', code: 'NAD' },
  ngn: { label: 'Nigerian Naira', flag: '🇳🇬', code: 'NGN' },
  nio: { label: 'Nicaraguan Córdoba', flag: '🇳🇮', code: 'NIO' },
  nok: { label: 'Norwegian Krone', flag: '🇳🇴', code: 'NOK' },
  npr: { label: 'Nepalese Rupee', flag: '🇳🇵', code: 'NPR' },
  nzd: { label: 'New Zealand Dollar', flag: '🇳🇿', code: 'NZD' },
  omr: { label: 'Omani Rial', flag: '🇴🇲', code: 'OMR' },
  pab: { label: 'Panamanian Balboa', flag: '🇵🇦', code: 'PAB' },
  pen: { label: 'Peruvian Sol', flag: '🇵🇪', code: 'PEN' },
  pgk: { label: 'Papua New Guinean Kina', flag: '🇵🇬', code: 'PGK' },
  php: { label: 'Philippine Peso', flag: '🇵🇭', code: 'PHP' },
  pkr: { label: 'Pakistani Rupee', flag: '🇵🇰', code: 'PKR' },
  pln: { label: 'Polish Zloty', flag: '🇵🇱', code: 'PLN' },
  pyg: { label: 'Paraguayan Guarani', flag: '🇵🇾', code: 'PYG' },
  qar: { label: 'Qatari Rial', flag: '🇶🇦', code: 'QAR' },
  ron: { label: 'Romanian Leu', flag: '🇷🇴', code: 'RON' },
  rsd: { label: 'Serbian Dinar', flag: '🇷🇸', code: 'RSD' },
  rub: { label: 'Russian Ruble', flag: '🇷🇺', code: 'RUB' },
  rwf: { label: 'Rwandan Franc', flag: '🇷🇼', code: 'RWF' },
  sar: { label: 'Saudi Riyal', flag: '🇸🇦', code: 'SAR' },
  sbd: { label: 'Solomon Islands Dollar', flag: '🇸🇧', code: 'SBD' },
  scr: { label: 'Seychellois Rupee', flag: '🇸🇨', code: 'SCR' },
  sdg: { label: 'Sudanese Pound', flag: '🇸🇩', code: 'SDG' },
  sek: { label: 'Swedish Krona', flag: '🇸🇪', code: 'SEK' },
  sgd: { label: 'Singapore Dollar', flag: '🇸🇬', code: 'SGD' },
  sll: { label: 'Sierra Leonean Leone', flag: '🇸🇱', code: 'SLL' },
  sos: { label: 'Somali Shilling', flag: '🇸🇴', code: 'SOS' },
  srd: { label: 'Surinamese Dollar', flag: '🇸🇷', code: 'SRD' },
  std: { label: 'São Tomé and Príncipe Dobra', flag: '🇸🇹', code: 'STD' },
  svc: { label: 'Salvadoran Colón', flag: '🇸🇻', code: 'SVC' },
  szl: { label: 'Swazi Lilangeni', flag: '🇸🇿', code: 'SZL' },
  thb: { label: 'Thai Baht', flag: '🇹🇭', code: 'THB' },
  tjs: { label: 'Tajikistani Somoni', flag: '🇹🇯', code: 'TJS' },
  tmt: { label: 'Turkmenistani Manat', flag: '🇹🇲', code: 'TMT' },
  tnd: { label: 'Tunisian Dinar', flag: '🇹🇳', code: 'TND' },
  top: { label: "Tongan Pa'anga", flag: '🇹🇴', code: 'TOP' },
  try: { label: 'Turkish Lira', flag: '🇹🇷', code: 'TRY' },
  ttd: { label: 'Trinidad and Tobago Dollar', flag: '🇹🇹', code: 'TTD' },
  twd: { label: 'New Taiwan Dollar', flag: '🇹🇼', code: 'TWD' },
  tzs: { label: 'Tanzanian Shilling', flag: '🇹🇿', code: 'TZS' },
  uah: { label: 'Ukrainian Hryvnia', flag: '🇺🇦', code: 'UAH' },
  ugx: { label: 'Ugandan Shilling', flag: '🇺🇬', code: 'UGX' },
  usd: { label: 'US Dollar', flag: '🇺🇸', code: 'USD' },
  uyu: { label: 'Uruguayan Peso', flag: '🇺🇾', code: 'UYU' },
  uzs: { label: 'Uzbekistan Som', flag: '🇺🇿', code: 'UZS' },
  vef: { label: 'Venezuelan Bolívar', flag: '🇻🇪', code: 'VEF' },
  vnd: { label: 'Vietnamese Dong', flag: '🇻🇳', code: 'VND' },
  vuv: { label: 'Vanuatu Vatu', flag: '🇻🇺', code: 'VUV' },
  wst: { label: 'Samoan Tala', flag: '🇼🇸', code: 'WST' },
  xaf: { label: 'CFA Franc BEAC', flag: '🌍', code: 'XAF' },
  xcd: { label: 'East Caribbean Dollar', flag: '🌎', code: 'XCD' },
  xof: { label: 'CFA Franc BCEAO', flag: '🌍', code: 'XOF' },
  xpf: { label: 'CFP Franc', flag: '🌏', code: 'XPF' },
  yer: { label: 'Yemeni Rial', flag: '🇾🇪', code: 'YER' },
  zar: { label: 'South African Rand', flag: '🇿🇦', code: 'ZAR' },
  zmw: { label: 'Zambian Kwacha', flag: '🇿🇲', code: 'ZMW' },
};

const STORAGE_KEY = 'calcsuite_enabled_currencies';

const DEFAULT_ENABLED = ['usd', 'eur', 'gbp', 'jpy', 'cad', 'aud', 'chf', 'cny', 'inr', 'mxn'];

export function getEnabledCurrencies() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) return JSON.parse(stored);
  } catch {}
  return DEFAULT_ENABLED;
}

export function setEnabledCurrencies(list) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(list));
  if (typeof window !== 'undefined') window.dispatchEvent(new Event('currencieschange'));
}