export const TIMEZONES = [
  { value: 'UTC', label: 'UTC — Coordinated Universal Time' },
  { value: 'America/New_York', label: 'New York — Eastern Time' },
  { value: 'America/Chicago', label: 'Chicago — Central Time' },
  { value: 'America/Denver', label: 'Denver — Mountain Time' },
  { value: 'America/Los_Angeles', label: 'Los Angeles — Pacific Time' },
  { value: 'America/Anchorage', label: 'Anchorage — Alaska Time' },
  { value: 'Pacific/Honolulu', label: 'Honolulu — Hawaii Time' },
  { value: 'America/Toronto', label: 'Toronto — Eastern Time (CA)' },
  { value: 'America/Vancouver', label: 'Vancouver — Pacific Time (CA)' },
  { value: 'America/Mexico_City', label: 'Mexico City — Central Time' },
  { value: 'America/Sao_Paulo', label: 'São Paulo — BRT' },
  { value: 'America/Buenos_Aires', label: 'Buenos Aires — ART' },
  { value: 'Europe/London', label: 'London — GMT/BST' },
  { value: 'Europe/Paris', label: 'Paris — Central European Time' },
  { value: 'Europe/Berlin', label: 'Berlin — Central European Time' },
  { value: 'Europe/Madrid', label: 'Madrid — Central European Time' },
  { value: 'Europe/Rome', label: 'Rome — Central European Time' },
  { value: 'Europe/Amsterdam', label: 'Amsterdam — Central European Time' },
  { value: 'Europe/Stockholm', label: 'Stockholm — Central European Time' },
  { value: 'Europe/Moscow', label: 'Moscow — MSK' },
  { value: 'Europe/Istanbul', label: 'Istanbul — TRT' },
  { value: 'Africa/Cairo', label: 'Cairo — Eastern European Time' },
  { value: 'Africa/Lagos', label: 'Lagos — West Africa Time' },
  { value: 'Africa/Johannesburg', label: 'Johannesburg — SAST' },
  { value: 'Asia/Dubai', label: 'Dubai — Gulf Standard Time' },
  { value: 'Asia/Karachi', label: 'Karachi — Pakistan Standard Time' },
  { value: 'Asia/Kolkata', label: 'Mumbai/Delhi — India Standard Time' },
  { value: 'Asia/Dhaka', label: 'Dhaka — Bangladesh Standard Time' },
  { value: 'Asia/Bangkok', label: 'Bangkok — Indochina Time' },
  { value: 'Asia/Singapore', label: 'Singapore — SGT' },
  { value: 'Asia/Shanghai', label: 'Shanghai — China Standard Time' },
  { value: 'Asia/Tokyo', label: 'Tokyo — Japan Standard Time' },
  { value: 'Asia/Seoul', label: 'Seoul — Korea Standard Time' },
  { value: 'Australia/Sydney', label: 'Sydney — AEST/AEDT' },
  { value: 'Australia/Melbourne', label: 'Melbourne — AEST/AEDT' },
  { value: 'Pacific/Auckland', label: 'Auckland — NZST/NZDT' },
];